src/Entity/OrderItem.php
<?php

namespace App\Entity;

use App\Repository\OrderItemRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=OrderItemRepository::class)
 */
class OrderItem
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
 
    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     * @Assert\GreaterThanOrEqual(1)
     * 
     */
    private $quantity = 1;

    /**
     * @ORM\ManyToOne(targetEntity=Products::class, inversedBy="orderItems")
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    /**
     * @ORM\ManyToOne(targetEntity=Order::class, inversedBy="items")
     */
    private $orderRef;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getProduct(): ?Products
    {
        return $this->product;
    }

    public function setProduct(?Products $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getOrderRef(): ?Order
    {
        return $this->orderRef;
    }

    public function setOrderRef(?Order $orderRef): self
    {
        $this->orderRef = $orderRef;

        return $this;
    }


    /**
     * Tests if the given item given corresponds to the same order item.
     *
     * @param OrderItem $item
     *
     * @return bool
     */
    public function equals(OrderItem $item): bool
    {
        return $this->getProduct()->getId() === $item->getProduct()->getId();
    }

    /**
     * Calculates the item total.
     *
     * @return float|int
     */
    public function getTotal(): float
    {
        return $this->getProduct()->getPriceAfter() * $this->getQuantity() /100;
    }

    public function getProductName()
    {
        return $this->product->getProductName();
    }
}

src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\Order;
use App\Form\EventListener\RemoveCartItemListener;
use App\Form\EventListener\ClearCartListener;
use App\Form\EventListener\PlaceOrderListener;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Security\Core\Security;

class CartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('items', CollectionType::class, [
                'entry_type' => CartItemType::class
            ])
            ->add('save', SubmitType::class)
            ->add('clear', SubmitType::class)
            ->add('checkout', SubmitType::class)
        ;
        $builder->addEventSubscriber(new RemoveCartItemListener());
        $builder->addEventSubscriber(new ClearCartListener());
        $builder->addEventSubscriber(new PlaceOrderListener());
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Form\CartType;
use App\Manager\CartManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\OrderRepository;
use App\Form\RegistrationFormType;

class CartController extends AbstractController
{
    /**
     * @Route("/cart", name="cart")
     */
    public function index(Request $request, CartManager $cartManager, AuthenticationUtils $authenticationUtils): Response
    {
        $user = $this->getUser();
        $userId = $user->getId();
        $form = $this->createForm(RegistrationFormType::class);

        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();

        $cart = $cartManager->getCurrentCart($user);
        $form = $this->createForm(CartType::class, $cart);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cart->setUpdatedAt(new \DateTime());
            $cart->setUserId($user);
            $cartManager->save($cart);

            return $this->redirectToRoute('cart');
        }

        return $this->render('cart/index.html.twig', [
            'last_username' => $lastUsername, 'error' => $error,
            'cart' => $cart,
            'registrationForm' => $form->createView(),
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/placed/orders", name="placedorders")
     */
    public function placedOrders(OrderRepository $orderRepository, AuthenticationUtils $authenticationUtils): Response
    {
        $form = $this->createForm(RegistrationFormType::class);
        // $orders = $this->getUser()->getOrders();
        $userId = $this->getUser()->getId();
        $orders = $orderRepository->getPlacedOrdersByUserId($userId);
        
        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('cart/placedOrders.html.twig', [
            'last_username' => $lastUsername, 'error' => $error,
            'cart' => $orders,
            'registrationForm' => $form->createView(),
        ]);
    }
}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}GroceryMart | Cart{% endblock %}

{% block body %}
    <div class="container mt-4">        
        {% if cart.items.count > 0 %}
            <div class="row mt-4">
                <!-- List of items -->
                <div class="col-md-8">
                    {{ form_start(form) }}
                    <div class="card">
                        <div class="card-header bg-dark text-white d-flex">
                            <h5>Items</h5>
                            <br/>
                            <div class="ml-auto">
                                {{ form_widget(form.save, {'attr': {'class': 'btn btn-warning'}}) }}
                                {{ form_widget(form.clear, {'attr': {'class': 'btn btn-light'}}) }}
                            </div>
                        </div>
                        <br/>
                        <ul class="list-group list-group-flush">
                            {% for item in form.items %}
                                <li class="list-group-item d-flex">
                                    <div class="flex-fill mr-2">
                                        <img src="/images/product/{{ item.vars.data.product.productImage }}" width="64" alt="Product image">
                                    </div>
                                    <div class="flex-fill mr-2">
                                        <h5 class="mt-0 mb-0">{{ item.vars.data.product.productName }}</h5>
                                        <div class="form-inline mt-2">
                                            <div class="form-group mb-0 mr-2">
                                                {{ form_widget(item.quantity, {
                                                    'attr': { 
                                                        'class': 'form-control form-control-sm ' ~ (item.quantity.vars.valid ? '' : 'is-invalid')
                                                    }
                                                }) }}
                                                <div class="invalid-feedback">
                                                    {{ form_errors(item.quantity) }}
                                                </div>
                                            </div>
                                            {{ form_widget(item.remove, {'attr': {'class': 'btn btn-dark btn-sm'}}) }}
                                        </div>
                                    </div>
                                    <div class="flex-fill mr-2 text-right">
                                        <b>₹ {{ item.vars.data.product.priceAfter /100  }}</b>
                                    </div>
                                </li>
                                
                                <br/>
                            {% endfor %}
                        </ul>
                    </div>
                    {# {{ dump(form) }} #}
                    
                </div>
                <!-- Summary -->
                <div class="col-md-4">
                    <div class="card mt-4 mt-md-0">
                        <h5 class="card-header bg-dark text-white">Summary</h5>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item d-flex justify-content-between">
                                <div><b>Total</b></div>
                                <span><b>₹ {{ cart.total }}</b></span>
                            </li>
                        </ul>
                        <div class="card-body">
                            {{ form_widget(form.checkout, {'attr': {'class': 'btn btn-warning'}}) }}
                        </div>
                    </div>
                </div>
                {{ form_end(form) }}
            </div>
        {% else %}
            <div class="alert alert-info" style="margin-top: 200px;">
                Your cart is empty. Go to the <a href="{{ path('index') }}">product list</a>.
            </div>
        {% endif %}
    </div>
    
{% endblock %}

templates/cart/placedOrders.html.twig
{% extends 'base.html.twig' %}

{% block title %}GroceryMart | Cart{% endblock %}

{% block body %}
    <div class="container mt-4">        
        {% if cart is empty %}
            <div class="alert alert-info" style="margin-top: 200px;">
                You yet not place any Order. Go to the <a href="{{ path('index') }}">product list</a>.
            </div>
        {% else %}
            <div class="row mt-4">
                <!-- List of items -->
                <div class="col-md-8">
                    <div class="card">
                        <br/>
                        <ul class="list-group list-group-flush">
                            {% for c in cart %}
                                <li class="list-group-item d-flex">
                                    <b>Order Id : {{ c.id }}</b>
                                    <br/>
                                    Order Status : {{ c.status }}
                                    {% for r in c.items %}
                                        <div class="flex-fill mr-2">
                                            <img src="/images/product/{{ r.product.productImage }}" width="64" alt="Product image">
                                        </div>
                                        <div class="flex-fill mr-2">
                                            {{ r.product.productName }}
                                            <div class="form-inline mt-2">
                                                <div class="form-group mb-0 mr-2">
                                                    Quantity : {{ r.quantity }}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="flex-fill mr-2 text-left">
                                            Product Price : ₹ {{ r.product.priceAfter /100  }}
                                        </div>
                                    {% endfor %}
                                    <div class="flex-fill mr-2 text-right">
                                        <b>Order Total Amount : ₹ {{ c.total }}</b>
                                    </div>
                                </li>
                                <br/>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
    
{% endblock %}