src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = ["ROLE_USER"];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="userId")
     */
    private $orders;

    /**
     * @ORM\OneToMany(targetEntity=UploadedDataFiles::class, mappedBy="user")
     */
    private $uploadedDataFiles;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->uploadedDataFiles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        // $roles[] = 'ROLE_USER';

        return $roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setUserId($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUserId() === $this) {
                $order->setUserId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|UploadedDataFiles[]
     */
    public function getUploadedDataFiles(): Collection
    {
        return $this->uploadedDataFiles;
    }

    public function addUploadedDataFile(UploadedDataFiles $uploadedDataFile): self
    {
        if (!$this->uploadedDataFiles->contains($uploadedDataFile)) {
            $this->uploadedDataFiles[] = $uploadedDataFile;
            $uploadedDataFile->setUser($this);
        }

        return $this;
    }

    public function removeUploadedDataFile(UploadedDataFiles $uploadedDataFile): self
    {
        if ($this->uploadedDataFiles->removeElement($uploadedDataFile)) {
            // set the owning side to null (unless already changed)
            if ($uploadedDataFile->getUser() === $this) {
                $uploadedDataFile->setUser(null);
            }
        }

        return $this;
    }
}

templates/base.html.twig
<html>
    <head>
        <meta charset="UTF-8">
        <title>
        {% block title %}
        {% endblock %}
        </title>

        {% block stylesheets %}
            <link href="{{ asset('frontend/css/font-awesome.css') }}" rel="stylesheet">
            <link href="{{ asset('frontend/css/bootstrap.css') }}" rel="stylesheet">   
            <link href="{{ asset('frontend/css/jquery.smartmenus.bootstrap.css') }}" rel="stylesheet">
            <link href="{{ asset('frontend/css/jquery.simpleLens.css') }}" rel="stylesheet" type="text/css" >    
            <link href="{{ asset('frontend/css/slick.css') }}" rel="stylesheet" type="text/css" >
            <link href="{{ asset('frontend/css/nouislider.css') }}" rel="stylesheet" type="text/css" >
            <link href="{{ asset('frontend/css/theme-color/default-theme.css') }}" id="switcher" rel="stylesheet">

            <link href="{{ asset('frontend/css/sequence-theme.modern-slide-in.css') }}" rel="stylesheet" media="all">
            <link href="{{ asset('frontend/css/style.css') }}" rel="stylesheet">    
            <link href="{{ asset('https://fonts.googleapis.com/css?family=Lato') }}"  rel='stylesheet' type='text/css'>
            <link href="{{ asset('https://fonts.googleapis.com/css?family=Raleway') }}"  rel='stylesheet' type='text/css'>
        {% endblock %}
    </head>
    <body>
        {% block loader %}
            <div id="wpf-loader-two">          
                <div class="wpf-loader-two-inner">
                    <span>Loading</span>
                </div>
            </div> 
            <!-- SCROLL TOP BUTTON -->
            <a class="scrollToTop" href="#"><i class="fa fa-chevron-up"></i></a>
        {% endblock %}

        {% block header %}
            {{ include('header.html.twig') }}    
        {% endblock %}

        {% block body %}
        {% endblock %}

        {% block login %}
                <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                    <div class="modal-content">                      
                        <div class="modal-body">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4>Login or Register</h4>
                        <div id="loginFormInModel">
                            <form class="aa-login-form" action="" method="POST">
                                {% if error %}
                                    <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                                {% endif %}
                                <label for="inputEmail">Email</label>
                                <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" required autofocus>
                                
                                <label for="inputPassword">Password</label>
                                <input type="password" name="password" id="inputPassword" class="form-control" required>
                                
                                <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">

                                <button class="aa-browse-btn" type="submit">Login</button>
                                
                                <label for="remember_me">
                                    <input type="checkbox" id="remember_me" name="_remember_me" checked/>
                                    Keep me logged in
                                </label>                            
                                <p class="aa-lost-password"><a href="#">Lost your password?</a></p>
                                <div class="aa-register-now">
                                    Don't have an account?<a id="register">Register now!</a>
                                </div>
                            </form>
                        </div>
                        <div id="registrationFormInModel" >{# start registrationform #}
                        {% if app.user %}
                        {% else %}
                        
                            {% for flashError in app.flashes('verify_email_error') %}
                                <div class="alert alert-danger" role="alert">{{ flashError }}</div>
                            {% endfor %}
                                    <h1 class="h3 mb-3 font-weight-normal" >Register</h1>
                                    {{ form_start(registrationForm,{'action': path('app_register')}) }}
                                        {{ form_label(registrationForm.email, 'Email') }}
                                        {{ form_widget(registrationForm.email) }}
                                        <br />
                                        {{ form_label(registrationForm.plainPassword, 'Password') }}
                                        {{ form_widget(registrationForm.plainPassword) }}
                                        <br />
                                        {{ form_row(registrationForm.agreeTerms) }}
                                        {{ form_widget(registrationForm.register, {'attr': {'class': 'btn btn-primary w-25'}}) }}
                                    {{ form_end(registrationForm) }}
                                    <div class="aa-register-now">
                                        Already have an account?<a id="loginHere">Login here!</a>
                                    </div>
                        {% endif %} 
                        </div>{# end registration #}



                        </div>                        
                    </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div>
        {% endblock %}

        {% block footer %}
            {{ include('footer.html.twig') }}
        {% endblock %}
            
        {% block javascripts %}
            
            <!-- jQuery library -->
            <script src="{{ asset('https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js') }}"></script>
            <!-- Include all compiled plugins (below), or include individual files as needed -->
            <script src="{{ asset('frontend/js/bootstrap.js') }}"></script>  
            <!-- SmartMenus jQuery plugin -->
            <script type="text/javascript" src="{{ asset('frontend/js/jquery.smartmenus.js') }}"></script>
            <!-- SmartMenus jQuery Bootstrap Addon -->
            <script type="text/javascript" src="{{ asset('frontend/js/jquery.smartmenus.bootstrap.js') }}"></script>  
            
            <script type="text/javascript" src="{{ asset('js/product.js') }}"></script>

            <!-- To Slider JS -->
            <script src="{{ asset('frontend/js/sequence.js') }}"></script>
            <script src="{{ asset('frontend/js/sequence-theme.modern-slide-in.js') }}"></script>  
            <!-- Product view slider -->
            <script type="text/javascript" src="{{ asset('frontend/js/jquery.simpleGallery.js') }}"></script>
            <script type="text/javascript" src="{{ asset('frontend/js/jquery.simpleLens.js') }}"></script>
            <!-- slick slider -->
            <script type="text/javascript" src="{{ asset('frontend/js/slick.js') }}"></script>
            <!-- Price picker slider -->
            <script type="text/javascript" src="{{ asset('frontend/js/nouislider.js') }}"></script>
            <!-- Custom js -->
            <script src="{{ asset('frontend/js/custom.js') }}"></script> 
            <!-- Login Model js -->
            <script src="{{ asset('js/modal.js') }}"></script>
        {% endblock %}
        
    </body>
</html>

templates/footer.html.twig
<!-- footer -->  
            <footer id="aa-footer">
                <!-- footer bottom -->
                <div class="aa-footer-top">
                <div class="container">
                    <div class="row">
                    <div class="col-md-12">
                    <div class="aa-footer-top-area">
                        <div class="row">
                        <div class="col-md-3 col-sm-6">
                            <div class="aa-footer-widget">
                            <h3>Main Menu</h3>
                            <ul class="aa-footer-nav">
                                <li><a href="#">Home</a></li>
                                <li><a href="#">Our Services</a></li>
                                <li><a href="#">Our Products</a></li>
                                <li><a href="#">About Us</a></li>
                                <li><a href="#">Contact Us</a></li>
                            </ul>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="aa-footer-widget">
                            <div class="aa-footer-widget">
                                <h3>Knowledge Base</h3>
                                <ul class="aa-footer-nav">
                                <li><a href="#">Delivery</a></li>
                                <li><a href="#">Returns</a></li>
                                <li><a href="#">Services</a></li>
                                <li><a href="#">Discount</a></li>
                                <li><a href="#">Special Offer</a></li>
                                </ul>
                            </div>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="aa-footer-widget">
                            <div class="aa-footer-widget">
                                <h3>Useful Links</h3>
                                <ul class="aa-footer-nav">
                                <li><a href="#">Site Map</a></li>
                                <li><a href="#">Search</a></li>
                                <li><a href="#">Advanced Search</a></li>
                                <li><a href="#">Suppliers</a></li>
                                <li><a href="#">FAQ</a></li>
                                </ul>
                            </div>
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="aa-footer-widget">
                            <div class="aa-footer-widget">
                                <h3>Contact Us</h3>
                                <address>
                                <p>Grocery Mart, Ring Road, Rajkot</p>
                                <p><span class="fa fa-phone"></span>(+91)88490-98896</p>
                                <p><span class="fa fa-envelope"></span>grocerymart@gmail.com</p>
                                </address>
                                <div class="aa-footer-social">
                                <a href="#"><span class="fa fa-facebook"></span></a>
                                <a href="#"><span class="fa fa-twitter"></span></a>
                                <a href="#"><span class="fa fa-google-plus"></span></a>
                                <a href="#"><span class="fa fa-youtube"></span></a>
                                </div>
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
                </div>
                <!-- footer-bottom -->
                <div class="aa-footer-bottom">
                <div class="container">
                    <div class="row">
                    <div class="col-md-12">
                    <div class="aa-footer-bottom-area">
                        <p>Designed by <a href="http://www.markups.io/">Parth Dadhaniya</a></p>
                        <div class="aa-footer-payment">
                        <span class="fa fa-cc-mastercard"></span>
                        <span class="fa fa-cc-visa"></span>
                        <span class="fa fa-paypal"></span>
                        <span class="fa fa-cc-discover"></span>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
                </div>
            </footer>
            <!-- / footer -->

templates/header.html.twig
            <header id="aa-header" >
                    <!-- start header top  -->
                    <div class="aa-header-top">
                    <div class="container">
                        <div class="row">
                        <div class="col-md-12">
                            <div class="aa-header-top-area">
                            <!-- start header top left -->
                            <div class="aa-header-top-left">
                                <!-- start cellphone -->
                                <div class="cellphone hidden-xs">
                                <p><span class="fa fa-phone"></span>(+91)94086-13173</p>
                                </div>
                                <!-- / cellphone -->
                            </div>
                            <!-- / header top left -->
                            <div class="aa-header-top-right">
                                <ul class="aa-head-top-nav-right">
                                
                                {% if app.user %}
                                    <li><a ><i class="fa fa-user" style="padding-right:5px;"></i>{{ app.user.username }}</a></li>
                                {% endif %} 
                                    
                                {# <li class="hidden-xs"><a href=""><i class="fa fa-heart" style="padding-right:5px;"></i>Wishlist</a></li> #}
                                
                                {% if app.user %}
                                    <li class="hidden-xs"><a href="{{ path('cart') }}"><i class="fa fa-shopping-cart" style="padding-right:5px;"></i> My Cart</a></li>
                                {% else %}
                                    <li class="hidden-xs"><a data-toggle="modal" id="parth" data-target="#login-modal"><i class="fa fa-shopping-cart" style="padding-right:5px;"></i> My Cart</a></li>
                                {% endif %}

                                {% if app.user %}
                                    <li class="hidden-xs"><a href="{{ path('placedorders') }}"><i class="fa fa-crosshairs" style="padding-right:5px;"></i>My Orders</a></li>
                                {% endif %}
                                
                                {% if app.user %}
                                    <li><a href="{{ path('app_logout') }}" ><i class="fa fa-lock" style="padding-right:5px;"></i>Logout</a></li>
                                {% else %}
                                    <li><a data-toggle="modal" id="parth" data-target="#login-modal"><i class="fa fa-lock" style="padding-right:5px;"></i>Login</a></li>
                                {% endif %}
                                
                                </ul>
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>
                    </div>
                    <!-- / header top  -->

                    <!-- start header bottom  -->
                    <div class="aa-header-bottom">
                    <div class="container">
                        <div class="row">
                        <div class="col-md-12">
                            <div class="aa-header-bottom-area">
                            <!-- logo  -->
                            <div class="aa-logo">
                                <!-- Text based logo -->
                                <a href="{{ path('index') }}">
                                <span class="fa fa-shopping-cart"></span>
                                <p>Grocery<strong>Mart</strong> <span>Your Shopping Partner</span></p>
                                </a>
                                <!-- img based logo -->
                                <!-- <a href="index.html"><img src="img/logo.jpg" alt="logo img"></a> -->
                            </div>
                            <!-- / logo  -->
                            <!-- cart box -->
                            <div class="aa-cartbox">
                                {% if app.user %}
                                    <a class="aa-cart-link" href="{{ path('cart') }}">
                                {% else %}
                                    <a class="aa-cart-link" data-toggle="modal" id="parth" data-target="#login-modal">
                                {% endif %}
                                <span class="fa fa-shopping-basket"></span>
                                <span class="aa-cart-title">SHOPPING CART</span>
                                <span class="aa-cart-notify">2</span>
                                </a>
                            </div>
                            <!-- / cart box -->
                            <!-- search box -->
                            <div class="aa-search-box">
                                <form action="">
                                <input type="text" name=""  placeholder="Search here ex. 'man' ">
                                <button type="submit"><span class="fa fa-search"></span></button>
                                </form>
                            </div>
                            <!-- / search box -->             
                            </div>
                        </div>
                        </div>
                    </div>
                    </div>
            </header>
                    <!-- menu -->
            <section id="menu">
                <div class="container">
                <div class="menu-area">
                    <!-- Navbar -->
                    <div class="navbar navbar-default" role="navigation">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        </button>          
                    </div>
                    <div class="navbar-collapse collapse">
                        <!-- Left nav -->
                        <ul class="nav navbar-nav">
                        <li><a href="{{ path('index') }}">Home</a></li>
                        {# <li><a href="#">Men <span class="caret"></span></a>
                            <ul class="dropdown-menu">                
                            <li><a href="#">Casual</a></li>
                            <li><a href="#">Sports</a></li>
                            <li><a href="#">Formal</a></li>
                            <li><a href="#">Standard</a></li>                                                
                            <li><a href="#">T-Shirts</a></li>
                            <li><a href="#">Shirts</a></li>
                            <li><a href="#">Jeans</a></li>
                            <li><a href="#">Trousers</a></li>
                            <li><a href="#">And more.. <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                <li><a href="#">Sleep Wear</a></li>
                                <li><a href="#">Sandals</a></li>
                                <li><a href="#">Loafers</a></li>                                      
                                </ul>
                            </li>
                            </ul>
                        </li>
                        <li><a href="#">Women <span class="caret"></span></a>
                            <ul class="dropdown-menu">  
                            <li><a href="#">Kurta & Kurti</a></li>                                                                
                            <li><a href="#">Trousers</a></li>              
                            <li><a href="#">Casual</a></li>
                            <li><a href="#">Sports</a></li>
                            <li><a href="#">Formal</a></li>                
                            <li><a href="#">Sarees</a></li>
                            <li><a href="#">Shoes</a></li>
                            <li><a href="#">And more.. <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                <li><a href="#">Sleep Wear</a></li>
                                <li><a href="#">Sandals</a></li>
                                <li><a href="#">Loafers</a></li>
                                <li><a href="#">And more.. <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                    <li><a href="#">Rings</a></li>
                                    <li><a href="#">Earrings</a></li>
                                    <li><a href="#">Jewellery Sets</a></li>
                                    <li><a href="#">Lockets</a></li>
                                    <li class="disabled"><a class="disabled" href="#">Disabled item</a></li>                       
                                    <li><a href="#">Jeans</a></li>
                                    <li><a href="#">Polo T-Shirts</a></li>
                                    <li><a href="#">SKirts</a></li>
                                    <li><a href="#">Jackets</a></li>
                                    <li><a href="#">Tops</a></li>
                                    <li><a href="#">Make Up</a></li>
                                    <li><a href="#">Hair Care</a></li>
                                    <li><a href="#">Perfumes</a></li>
                                    <li><a href="#">Skin Care</a></li>
                                    <li><a href="#">Hand Bags</a></li>
                                    <li><a href="#">Single Bags</a></li>
                                    <li><a href="#">Travel Bags</a></li>
                                    <li><a href="#">Wallets & Belts</a></li>                        
                                    <li><a href="#">Sunglases</a></li>
                                    <li><a href="#">Nail</a></li>                       
                                    </ul>
                                </li>                   
                                </ul>
                            </li>
                            </ul>
                        </li>
                        <li><a href="#">Kids <span class="caret"></span></a>
                            <ul class="dropdown-menu">                
                            <li><a href="#">Casual</a></li>
                            <li><a href="#">Sports</a></li>
                            <li><a href="#">Formal</a></li>
                            <li><a href="#">Standard</a></li>                                                
                            <li><a href="#">T-Shirts</a></li>
                            <li><a href="#">Shirts</a></li>
                            <li><a href="#">Jeans</a></li>
                            <li><a href="#">Trousers</a></li>
                            <li><a href="#">And more.. <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                <li><a href="#">Sleep Wear</a></li>
                                <li><a href="#">Sandals</a></li>
                                <li><a href="#">Loafers</a></li>                                      
                                </ul>
                            </li>
                            </ul>
                        </li>
                        <li><a href="#">Sports</a></li>
                        <li><a href="#">Digital <span class="caret"></span></a>
                            <ul class="dropdown-menu">                
                            <li><a href="#">Camera</a></li>
                            <li><a href="#">Mobile</a></li>
                            <li><a href="#">Tablet</a></li>
                            <li><a href="#">Laptop</a></li>                                                
                            <li><a href="#">Accesories</a></li>                
                            </ul>
                        </li>
                        <li><a href="#">Furniture</a></li>            
                        <li><a href="blog-archive.html">Blog <span class="caret"></span></a>
                            <ul class="dropdown-menu">                
                            <li><a href="blog-archive.html">Blog Style 1</a></li>
                            <li><a href="blog-archive-2.html">Blog Style 2</a></li>
                            <li><a href="blog-single.html">Blog Single</a></li>                
                            </ul>
                        </li>
                        <li><a href="contact.html">Contact</a></li>
                        <li><a href="#">Pages <span class="caret"></span></a>
                            <ul class="dropdown-menu">                
                            <li><a href="product.html">Shop Page</a></li>
                            <li><a href="product-detail.html">Shop Single</a></li>                
                            <li><a href="404.html">404 Page</a></li>                
                            </ul>
                        </li> #}
                        </ul>
                    </div><!--/.nav-collapse -->
                    </div>
                </div>       
                </div>
            </section>

            

templates/side.html.twig
<section>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="left-sidebar">
                                <h2 style="padding-top:30px;">Category</h2>
                                <div class="price-range">
                                    <h2>Price Range</h2>
                                    <div class="well text-center">
                                        <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
                                        <b class="pull-left">$ 0</b> <b class="pull-right">$ 600</b>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>